[build-system]
requires = [ "poetry-core>=1.9.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "requests-unixsocket2"
version = "0.4.1"
description = "Use requests to talk HTTP via a UNIX domain socket"
authors = ["thelab <thelabdev@thelab.co>"]
readme = "README.md"
homepage = "https://gitlab.com/thelabnyc/requests-unixsocket2"
repository = "https://gitlab.com/thelabnyc/requests-unixsocket2"
license = "ISC"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]


[[tool.poetry.packages]]
include = "requests_unixsocket"

[tool.poetry.dependencies]
python = "^3.8.1"
requests = "^2.32.3"
urllib3 = ">=2.2.2,<3.0"

[tool.poetry.group.dev.dependencies]
coverage = {extras = ["toml"], version = "^7.6.0"}
flake8 = "^7.1.0"
pytest = "^8.2.2"
waitress = "^3.0.0"
mypy = "^1.10.1"
types-requests = "^2.32.0.20240521"
types-waitress = "^3.0.0.20240423"

[tool.mypy]
python_version = "3.8"

[tool.pytest.ini_options]
addopts = "--tb=short"

[tool.isort]
profile = "black"
from_first = true

[tool.coverage.run]
branch = true
source_pkgs = ["requests_unixsocket"]

[tool.coverage.report]
show_missing = true
ignore_errors = true
