[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "requests-unixsocket2"
version = "0.4.0"
description = "Use requests to talk HTTP via a UNIX domain socket"
authors = ["thelab <thelabdev@thelab.co>"]
readme = "README.md"
homepage = "https://gitlab.com/thelabnyc/requests-unixsocket2"
repository = "https://gitlab.com/thelabnyc/requests-unixsocket2"
license = "ISC"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]


[[tool.poetry.packages]]
include = "requests_unixsocket"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.0.0"
urllib3 = ">=1.0,<3.0"

[tool.poetry.group.dev.dependencies]
coverage = {extras = ["toml"], version = "^7.4.1"}
flake8 = "^7.0.0"
pytest = "^8.2.1"
waitress = "^3.0.0"

[tool.pytest.ini_options]
addopts = "--tb=short"

[tool.isort]
profile = "black"
from_first = true

[tool.coverage.run]
branch = true
source_pkgs = ["requests_unixsocket"]

[tool.coverage.report]
show_missing = true
ignore_errors = true
